- yay:
    # Docker
    - docker
    - docker-compose

    # Chromium
    - ungoogled-chromium

    # Spotify
    - spotify
    - spicetify-cli
    - spotifyd

    - flameshot

    - discord

    - syncthing-bin

    # Development
    - android-studio
    - vscodium-bin
    - vscodium-bin-marketplace

    - steam

    - multimc-bin

    # Utils
    - htop
    - bottom

    - neofetch

    - doggo-bin
    - net-tools

    - unzip

    - openssh

- vscode:
    esbenp.prettier-vscode:
      status: install
    ms-vscode.atom-keybindings:
      status: install
    pkief.material-icon-theme:
      status: install
    dart-code.dart-code:
      status: install
    dart-code.flutter:
      status: install
    orta.vscode-jest:
      status: install
    ms-azuretools.vscode-docker:
      status: install
    syler.sass-indented:
      status: install
    redhat.vscode-xml:
      status: install
    dbaeumer.vscode-eslint:
      status: install
    seansassenrath.vscode-theme-superonedark:
      status: install
    mosbasik.sxhkdrc-syntax:
      status: install
    dlasagno.rasi:
      status: install
